name: Ensure no git diff exists
description: Use git diff --exit-code to ensure stability of commands and to reduce flakiness in CI.
branding:
  icon: award
  color: green

# None
inputs: {}

runs:
  using: composite
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # - name: "Debug action directory (CWD)"
    #   shell: bash
    #   run: ls -la

    # - name: "Debug action directory (GITHUB_ACTION_PATH)"
    #   shell: bash
    #   run: ls -la $GITHUB_ACTION_PATH

    - name: "Check if a git diff exists. Error if it does"
      shell: bash
      run: $GITHUB_ACTION_PATH/no-git-diff.sh
