name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
      - run: pnpm lint

  test_success:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./

  test_failure:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rm .prettierignore 
      - uses: ./
        id: self
        continue-on-error: true
      - if: always()
        run: |
          if "[[ ${{ steps.self.conclusion }}" == "failure" ]]; then
            echo "Successfully failed"
            exit 0;
          else
            echo "Unsuccessfully failed. Expected failure."
            exit 1
          fi
